# Generated by Django 4.2.3 on 2025-11-01 17:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('clothes', 'CLOTHES'), ('accessories', 'ACCESSORIES'), ('grooming', 'GROOMING'), ('electronics', 'ELECTRONICS')], max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)])),
                ('product_image', models.ImageField(upload_to='products/')),
                ('in_cart', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('date_of_purchase', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('received', 'RECEIVED'), ('accepted', 'ACCEPTED'), ('declined', 'DECLINED'), ('shipped', 'SHIPPED'), ('delivered', 'DELIVERED')], default='received', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.product')),
            ],
        ),
    ]
